DROP DATABASE IF EXISTS Testing_System_Assignment_1SonPC;
Create DATABASE Testing_System_Assignment_1SonPC;
use Testing_System_Assignment_1SonPC;

Drop TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT(
DepartmentID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DepartmentName VARCHAR(20)
);


Drop TABLE IF EXISTS POSITION1;
CREATE TABLE POSITION1(
PositionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PositinonName VARCHAR (10)
);


DROP TABLE IF EXISTS ACCOUNT1;
CREATE TABLE ACCOUNT1(
AccountID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Email VARCHAR (50) NOT NULL UNIQUE,
Usename VARCHAR (10) NOT NULL UNIQUE,
FullName NVARCHAR (20) NOT NULL,
DepartmentID INT NOT NULL,
PositionID INT NOT NULL,
CreateDate DATE
);


DROP TABLE IF EXISTS GROUP1;
CREATE TABLE GROUP1(
GroupID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
GroupName VARCHAR (10) NOT NULL UNIQUE,
CreatorID INT NOT NULL,
CreateDate DATETIME DEFAULT (28/10/2021)
);
DROP TABLE IF EXISTS GROUPACCOUNT;
CREATE TABLE GROUPACCOUNT(
GroupID INT NOT NULL,
AccountID INT NOT NULL,
JoinDate DATETIME DEFAULT (28/10/2021),
PRIMARY KEY(GroupID, AccountID)
);
DROP TABLE IF EXISTS TYPEQUESTION;
CREATE TABLE TYPEQUESTION(
TypeID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TypeName ENUM ('Essay, Multiple-Choice) NOT NULL )'
));
DROP TABLE IF EXISTS CATEGORYQUESTION;
CREATE TABLE CATEGORYQUESTION(
CategoryID INT AUTO_INCREMENT PRIMARY KEY,
CategoryName ENUM ('Java, Net, Sql, Ruby, Postman) NOT NULL UNIQUE)')
);
DROP TABLE IF EXISTS QUESTION;
CREATE TABLE QUESTION(
QuestionID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Content VARCHAR (200) NOT NULL UNIQUE,
CategoryID INT NOT NULL,
TypeID INT NOT NULL,
CreatorID INT NOT NULL,
CreateDate DATE
);
DROP TABLE IF EXISTS ANSWER;
CREATE TABLE ANSWER(
AnswerID INT AUTO_INCREMENT PRIMARY KEY,
Content VARCHAR (200) NOT NULL UNIQUE,
QuestionID INT NOT NULL,
IsCrroct ENUM ('True,Fail) NOT NULL)')
);
DROP TABLE IF EXISTS EXAM;
CREATE TABLE EXAM(
ExamID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Code1 INT,
Tile VARCHAR (20),
CategoryID INT,
Duration DATETIME,
CreatorID INT,
CreatDate DATE
);

DROP TABLE IF EXISTS EXAMQUESTION;
CREATE TABLE EXAMQUESTION(
ExamID INT NOT NULL,
QuestionID INT NOT NULL
);












