#account
CONSTRAINT lien_ket_1 FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentID),
CONSTRAINT lien_ket_2 FOREIGN KEY (PositionID) REFERENCES Position1(PositonID)
#BAI GRUOP1
CONSTRAINT lien_ket_3 FOREIGN KEY (CreatorID) REFERENCES ACCOUNT1(CreatorID)
#BAIGROUPACCOUNT
CONSTRAINT lien_ket_4 FOREIGN KEY (GroupID) REFERENCES GROUP1(GroupID),
CONSTRAINT lien_ket_5 FOREIGN KEY (AccountID) REFERENCES ACCOUNT1(AccountID)
#BAIQUESTION
CONSTRAINT lien_ket_6 FOREIGN KEY (CategoryID) REFERENCES CATEGORYQUESTION(CategoryID),
CONSTRAINT lien_ket_7 FOREIGN KEY (TypeID) REFERENCES TYPEQUESTION(TypeID),
CONSTRAINT lien_ket_8 FOREIGN KEY (CreateID) REFERENCES GROUP1(CreateId),
CONSTRAINT lien_ket_9 FOREIGN KEY (CreaDate) REFERENCES GROUP1(CreaDate)
#BAI ANSWER
CONSTRAINT lien_ket_10 FOREIGN KEY (QuestionID) REFERENCES QUESTION(QuestionID)
#BAI EXAM
CONSTRAINT lien_ket_11 FOREIGN KEY (CategoryID) REFERENCES CATEGORYQUESTION(CategoryID),
CONSTRAINT lien_ket_12 FOREIGN KEY (CreatorID) REFERENCES Account1(CreatorID),
CONSTRAINT lien_ket_13 FOREIGN KEY (CreateDate) REFERENCES GROUP1(CreateDate)
#BAI EXAMQUESTION
CONSTRAINT lien_ket_14 FOREIGN KEY (ExamID) REFERENCES EXAM(ExamID),
CONSTRAINT lien_ket_15 FOREIGN KEY (QuestionID) REFERENCES QUESTION(QuestionID)